baseURL = "https://123.kozilla.io/"
languageCode = "zh-CN"
title = "Koyeo's site"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
# [params]
#   author = "iplaycode"
#   description = "Webstack Hugo"
[params.search]
  enable = true
[params.darkmode]
  enable = false